In [20]:
import numpy as np
import math
#import networkx as nx


**Create Lists**

In [21]:
A = np.arange(0,20,1)
B = np.arange(0,40,2)
C = np.arange(1,40,2)


In [29]:
nums = np.arange(2,20,1)
nums

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [30]:
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

In [33]:

D = np.array([num for num in range(2, 100) if is_prime(num)])[:20]
D

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71])

In [34]:
E = np.arange(5,105,5)
E

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [35]:
Lists = [A, B, C, D, E]
for i in range(len(Lists)):
    print(Lists[i])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71]
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


**Create Vertexes and Edges**

In [2]:
pip install networkx


  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)


In [37]:
import networkx as nx

  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [12 lines of output]
  + meson setup C:\Users\Beck\AppData\Local\Temp\pip-install-2btpyxvm\contourpy_049ce6a137c64da382c6ee06977677de C:\Users\Beck\AppData\Local\Temp\pip-install-2btpyxvm\contourpy_049ce6a137c64da382c6ee06977677de\.mesonpy-r96ez0au\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=C:\Users\Beck\AppData\Local\Temp\pip-install-2btpyxvm\contourpy_049ce6a137c64da382c6ee06977677de\.mesonpy-r96ez0au\build\meson-python-native-file.ini
  The Meson build system
  Version: 1.2.0
  Source dir: C:\Users\Beck\AppData\Local\Temp\pip-install-2btpyxvm\contourpy_049ce6a137c64da382c6ee06977677de
  Build dir: C:\Users\Beck\AppData\Local\Temp\pip-install-2btpyxvm\contourpy_049ce6a137c64da382c6ee06977677de\.mesonpy-r96ez0au\build
  Build type: native build
  Project name: contourpy
  Project version: 1.1.0
  
  ..\..\meson.build:1:0: 

  Using cached matplotlib-3.7.2-cp38-cp38-win32.whl (7.3 MB)
     -------------------------------------- 50.5/50.5 MB 148.6 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached numpy-1.24.4-cp38-cp38-win32.whl (12.5 MB)
  Using cached contourpy-1.1.0.tar.gz (13.4 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'


In [4]:
G=nx.Graph()

In [ ]:
G.add_nodes_from(A)
