<a href="https://colab.research.google.com/github/JustKeepPlay/Creative-Lab/blob/main/Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import math
#import networkx as nx


In [3]:
A = np.arange(0,20,1)
B = np.arange(0,40,2)
C = np.arange(1,40,2)

In [4]:
nums = np.arange(2,20,1)
nums

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [5]:
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

In [6]:
D = np.array([num for num in range(2, 100) if is_prime(num)])[:20]
D

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71])

In [7]:
E = np.arange(5,105,5)
E

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [8]:
Lists = [A, B, C, D, E]
for i in range(len(Lists)):
    print(Lists[i])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71]
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [15]:
allNum = np.concatenate((A,B,C,D,E))
Vertices = set(allNum)
print(Vertices)
print(len(Vertices))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 43, 45, 47, 50, 53, 55, 59, 60, 61, 65, 67, 70, 71, 75, 80, 85, 90, 95, 100}
61


In [10]:
pip install networkx

In [11]:
import matplotlib.pyplot as plt
import networkx as nx

In [12]:
G=nx.Graph()

In [19]:
edgesA = [(A[i], A[i + 1]) for i in range(len(A) - 1)]
edgesB = [(B[i], B[i + 1]) for i in range(len(B) - 1)]
edgesC = [(C[i], C[i + 1]) for i in range(len(C) - 1)]
edgesD = [(D[i], D[i + 1]) for i in range(len(D) - 1)]
edgesE = [(E[i], E[i + 1]) for i in range(len(E) - 1)]

In [24]:
edgesA

[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 6),
 (6, 7),
 (7, 8),
 (8, 9),
 (9, 10),
 (10, 11),
 (11, 12),
 (12, 13),
 (13, 14),
 (14, 15),
 (15, 16),
 (16, 17),
 (17, 18),
 (18, 19)]